"use client";

import dynamic from "next/dynamic";
import { Suspense } from "react";
import Link from "next/link";
import { ArrowRight, Coins, PlusCircle, ShieldCheck } from "lucide-react";
import { motion } from "framer-motion";

const Obelisk3DCanvasLazy = dynamic(
  () => import("./Obelisk3DCanvas").then((mod) => mod.Obelisk3DCanvas),
  { ssr: false }
);

function ObeliskFallback() {
  return (
    <div className="w-full h-full min-h-[380px] flex items-center justify-center">
      <div className="w-40 h-40 rounded-full border border-[#8B7BF0]/30 animate-pulse bg-[#8B7BF0]/5" />
    </div>
  );
}

export function UseCaseSplit() {
  return (
    <section className="py-24 px-4 sm:px-6 lg:px-8 bg-[#0A0A0A] border-b border-[#1F2933]">
      <div className="max-w-7xl mx-auto grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
        {/* Left Side: Content */}
        <motion.div
          initial={{ opacity: 0, x: -30 }}
          whileInView={{ opacity: 1, x: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="lg:col-span-6 space-y-6"
        >
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-[#8B7BF0]/10 border border-[#8B7BF0]/30 text-xs font-semibold text-[#8B7BF0]">
            <Coins className="w-3.5 h-3.5" />
            <span>Markets in Action</span>
          </div>

          <h2 className="text-3xl sm:text-5xl font-bold tracking-tight text-[#E6EDF3] leading-tight">
            Permissionless <br />
            <span className="text-[#8B7BF0]">Creator Markets</span>
          </h2>

          <p className="text-base sm:text-lg text-[#8A97A6] font-normal leading-relaxed">
            Anyone can launch a custom prediction market on Oracle Pit by staking a bond on Base. As market creator, you earn a perpetual percentage cut of all trading fees generated by your market.
          </p>

          <div className="space-y-4 pt-2">
            <div className="flex items-start gap-3">
              <div className="w-6 h-6 rounded-full bg-[#F5A623]/20 text-[#F5A623] flex items-center justify-center flex-shrink-0 mt-0.5 font-bold text-xs">
                1
              </div>
              <div>
                <h4 className="text-sm font-semibold text-[#E6EDF3]">Stake a Bond</h4>
                <p className="text-xs text-[#8A97A6]">Propose resolution rules and stake initial ETH/USDC bond.</p>
              </div>
            </div>

            <div className="flex items-start gap-3">
              <div className="w-6 h-6 rounded-full bg-[#3DDC84]/20 text-[#3DDC84] flex items-center justify-center flex-shrink-0 mt-0.5 font-bold text-xs">
                2
              </div>
              <div>
                <h4 className="text-sm font-semibold text-[#E6EDF3]">Pre-Sale Backing</h4>
                <p className="text-xs text-[#8A97A6]">Community backs your market proposal into live trading status.</p>
              </div>
            </div>

            <div className="flex items-start gap-3">
              <div className="w-6 h-6 rounded-full bg-[#8B7BF0]/20 text-[#8B7BF0] flex items-center justify-center flex-shrink-0 mt-0.5 font-bold text-xs">
                3
              </div>
              <div>
                <h4 className="text-sm font-semibold text-[#E6EDF3]">Earn Trading Cut</h4>
                <p className="text-xs text-[#8A97A6]">Collect recurring fee revenue as traders buy and sell outcome shares.</p>
              </div>
            </div>
          </div>

          <div className="pt-4 flex items-center gap-4">
            <Link
              href="/create"
              className="inline-flex items-center gap-2 px-6 py-3.5 rounded-full bg-[#8B7BF0] hover:bg-[#8B7BF0]/90 text-[#0A0A0A] font-bold text-sm transition-all duration-200 shadow-xl shadow-[#8B7BF0]/20 group"
            >
              Propose a Market
              <PlusCircle className="w-4 h-4 group-hover:rotate-90 transition-transform duration-300" />
            </Link>

            <Link
              href="/presale"
              className="inline-flex items-center gap-2 text-sm font-semibold text-[#8A97A6] hover:text-[#E6EDF3] transition-colors group"
            >
              Browse Pre-Sale Markets
              <ArrowRight className="w-4 h-4 text-[#F5A623] group-hover:translate-x-1 transition-transform" />
            </Link>
          </div>
        </motion.div>

        {/* Right Side: Interactive 3D Obelisk / Oracle Pillar Model */}
        <motion.div
          initial={{ opacity: 0, x: 30 }}
          whileInView={{ opacity: 1, x: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6, delay: 0.2 }}
          className="lg:col-span-6 bg-[#12181F] rounded-3xl border border-[#1F2933] p-8 shadow-2xl relative overflow-hidden flex items-center justify-center"
        >
          <div className="absolute inset-0 bg-gradient-to-tr from-[#8B7BF0]/10 via-transparent to-[#F5A623]/10 pointer-events-none" />

          {/* 3D Obelisk Canvas */}
          <Suspense fallback={<ObeliskFallback />}>
            <Obelisk3DCanvasLazy />
          </Suspense>

          {/* Floating Card Overlay */}
          <div className="absolute bottom-6 left-6 right-6 p-4 rounded-xl bg-[#0A0A0A]/90 border border-[#1F2933] backdrop-blur-md flex items-center justify-between text-xs">
            <div className="flex items-center gap-2">
              <ShieldCheck className="w-4 h-4 text-[#3DDC84]" />
              <span className="font-semibold text-[#E6EDF3]">Creator Protocol Active</span>
            </div>
            <span className="font-mono text-[#F5A623]">0.5% Fee Share</span>
          </div>
        </motion.div>
      </div>
    </section>
  );
}
